const std = @import("std");

pub const c = @import("c.zig").c;

pub const return_values = enum(u32) {
    TX_SUCCESS = c.TX_SUCCESS,
    TX_DELETED = c.TX_DELETED,
    TX_POOL_ERROR = c.TX_POOL_ERROR,
    TX_PTR_ERROR = c.TX_PTR_ERROR,
    TX_WAIT_ERROR = c.TX_WAIT_ERROR,
    TX_SIZE_ERROR = c.TX_SIZE_ERROR,
    TX_GROUP_ERROR = c.TX_GROUP_ERROR,
    TX_NO_EVENTS = c.TX_NO_EVENTS,
    TX_OPTION_ERROR = c.TX_OPTION_ERROR,
    TX_QUEUE_ERROR = c.TX_QUEUE_ERROR,
    TX_QUEUE_EMPTY = c.TX_QUEUE_EMPTY,
    TX_QUEUE_FULL = c.TX_QUEUE_FULL,
    TX_SEMAPHORE_ERROR = c.TX_SEMAPHORE_ERROR,
    TX_NO_INSTANCE = c.TX_NO_INSTANCE,
    TX_THREAD_ERROR = c.TX_THREAD_ERROR,
    TX_PRIORITY_ERROR = c.TX_PRIORITY_ERROR,
    TX_NO_MEMORY = c.TX_NO_MEMORY,
    //TX_START_ERROR = c.TX_START_ERROR,
    TX_DELETE_ERROR = c.TX_DELETE_ERROR,
    TX_RESUME_ERROR = c.TX_RESUME_ERROR,
    TX_CALLER_ERROR = c.TX_CALLER_ERROR,
    TX_SUSPEND_ERROR = c.TX_SUSPEND_ERROR,
    TX_TIMER_ERROR = c.TX_TIMER_ERROR,
    TX_TICK_ERROR = c.TX_TICK_ERROR,
    TX_ACTIVATE_ERROR = c.TX_ACTIVATE_ERROR,
    TX_THRESH_ERROR = c.TX_THRESH_ERROR,
    TX_SUSPEND_LIFTED = c.TX_SUSPEND_LIFTED,
    TX_WAIT_ABORTED = c.TX_WAIT_ABORTED,
    TX_WAIT_ABORT_ERROR = c.TX_WAIT_ABORT_ERROR,
    TX_MUTEX_ERROR = c.TX_MUTEX_ERROR,
    TX_NOT_AVAILABLE = c.TX_NOT_AVAILABLE,
    TX_NOT_OWNED = c.TX_NOT_OWNED,
    TX_INHERIT_ERROR = c.TX_INHERIT_ERROR,
    TX_NOT_DONE = c.TX_NOT_DONE,
    TX_CEILING_EXCEEDED = c.TX_CEILING_EXCEEDED,
    TX_INVALID_CEILING = c.TX_INVALID_CEILING,
    TX_FEATURE_NOT_ENABLED = c.TX_FEATURE_NOT_ENABLED,
};

pub const osError = error{
    osError,
};

pub fn osErrorMap(osStatus: c.UINT) osError!void {
    return switch (osStatus) {
        c.TX_SUCCESS => {},
        else => osError.osError,
    };
}

pub const tick_value_t = c.ULONG;
